# Site
repository: eshaan7/resume
favicon: assets/favicon.png

# Personal info
name: Eshaan Bansal
title: Web Pentester | CTF player | Fullstack Developer | Sophomore at USICT
email: eshaanbansal@protonmail.com
resume: https://drive.google.com/file/d/1BLJXR_rFFLP7wobE-Fog363JcbH5uttQ/view
website: https://eshaan7.github.io/

# Social links
twitter_username: mask0fmydisguis
github_username: eshaan7
medium_username: eshaan7
instagram_username: maskofmydisguise
linkedin_username: eshaan7
# youtube_username: jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: assets/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  I am a **Sophomore** pursuing B.Tech in IT at [USICT](https://ipu.ac.in/usict), GGSIPU Main Campus. 

  My CS interests currently lie in <mark>Cybersecurity</mark> and <mark>Web Development</mark>.

  The most interesting things happening in my life, right now, academically speaking are:
  - Working as a [<mark>Fullstack web development</mark>](#experience) intern at <a href="https://zoai.in/" target="_blank">Zoai Technologies</a>
  - Serving as part of the core team at DEF CON NCR group, DC91120
  - Serving as the General Secretary at the cyber security club, <a href="https://techspace.club/" target="_blank">Rooters</a> at USICT.

  I am actively looking for cybersecurity and research internships for winter 2019. I am available remotely too.

  _A pdf version of my resume is available [here](https://drive.google.com/file/d/1BLJXR_rFFLP7wobE-Fog363JcbH5uttQ/view)._

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# Achievements Section
achievements_title: "Few things I am proud of"

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  I love learning new things, and **blogs** are my way of doing so. I am an avid reader. 
  
  I am an absolute nerd and have worked on various technologies including Linux, Git, Heroku, Docker, Google Cloud Platform, Raspberry Pi and Arduino microcontroller.

  Alongside my interests in cybersecurity and web development some of my other interests and hobbies are:
  - Food, lots of it.
  - TV Shows
  - Blockchain and Cryptocurrencies

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
