# Site
repository: eshaan7/eshaan7.github.io
favicon: assets/glider.ico

# Personal info
name: Eshaan Bansal
title: Security Software Developer
email: eshaan7bansal@gmail.com
resume: https://drive.google.com/file/d/1BLJXR_rFFLP7wobE-Fog363JcbH5uttQ/view
website: https://eshaan7.github.io/
blog: http://eshaan7.github.io/blog/

# Social links
twitter_username: eshaan7_
github_username: eshaan7
# medium_username: eshaan7
# instagram_username: maskofmydisguise
linkedin_username: eshaan7
# youtube_username: jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: assets/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  I am Eshaan, a 23 year old software engineer based in India. In my short lived career, I have worked on various kinds of software products involving cyber threat intelligence, malware analysis, content delivery networks, social media networks, developer tools, static analysis, restaurant management platform and more.

  #### Continuous Open-Source Work
  - ü¶â  <a href="https://github.com/certego/IntelOwl" target="_blank">**IntelOwl**</a>: Principal maintainer of the project under <a href="https://www.honeynet.org/" target="_blank" >The Honeynet Project</a>. (GSoC'20 participant, GSoC'21,'22 mentor)

 #### Packages written by me:

 ##### ‚öõÔ∏è JavaScript
 - <a target="_blank" href="https://github.com/certego/certego-ui">**certego-ui**</a>: Design framework and components library built over React.js and reactstrap.

 ##### üêç Python
 - <a target="_blank" href="https://github.com/Eshaan7/Flask-Shell2HTTP">**Flask-Shell2HTTP**</a>:
 A minimalist Flask extension that serves as a REST/HTTP wrapper for python's subprocess API. Map shell commands to flask's endpoints and query asynchronously. 
 - <a target="_blank" href="https://github.com/Eshaan7/django-rest-durin">**Django-Rest-Durin**</a>: 
 Per API Client Token Authentication for Django Rest Framework.
 - <a target="_blank" href="https://github.com/Eshaan7/click-creds">**click-creds**</a>: 
 Pluggable credentials storage and management for click CLI apps.
 - <a target="_blank" href="https://github.com/certego/certego-saas">**certego-saas**</a>: Python package consisting of common and re-usable django apps required by all of certego SaaS products.
 - <a target="_blank" href="https://github.com/certego/django-rest-client">**django-rest-client**</a>: Framework for rapid building of ease-of-use, type-hinted and self-documented API clients in python.

 #### Work Experience:
 - SDE III @ [DeepSource](https://deepsource.com) (as [@eshaan-deepsource](https://github.com/eshaan-deepsource)).
 - (Past) Software Engineer (Threat Intel) @ [Certego](https://www.certego.net/en/).
 - (Past) SDE intern @ [Trell](https://trell.co).
 
# The most interesting things happening in my life, right now, academically speaking are:

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# Achievements Section
achievements_title: "Few things I am proud of"

# Volunteering Experience section
volunteering_experience_title: "Infosec Community"

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  I love learning new things, and **blogs** are my way of doing so. I am an avid reader. 
  
  I am an absolute nerd and have worked on various technologies including Linux, Git, Heroku, Docker, Google Cloud Platform, Raspberry Pi and Arduino microcontroller.

  Alongside my interests in cybersecurity and web development some of my other interests and hobbies are:
  - Food, lots of it.
  - TV Shows
  - Blockchain and Cryptocurrencies

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
#  - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
